version: 2

linters-settings:
  dupl:
    threshold: 100
  goconst:
    min-len: 2
    min-occurrences: 2
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
  gocyclo:
    min-complexity: 15
  goimports:
    local-prefixes: github.com/StanleyXie/tfpipboy
  govet:
    settings:
      shadow:
        strict: true
  lll:
    line-length: 140
  misspell:
    locale: US

linters:
  disable-all: true
  enable:
    - bodyclose
    - errcheck
    - goconst
    - gocyclo
    - gosec
    - govet
    - ineffassign
    - lll
    - misspell
    - staticcheck
    - unused
    - gocritic
    - revive

issues:
  exclude-use-default: false
  exclude-dirs:
    - vendor
  max-issues-per-linter: 0
  max-same-issues: 0

run:
  timeout: 5m
